# En este archivo configuramos el sonar-scanner para que sepa dónde están los archivos fuente, los tests, y dónde generar los reportes de cobertura.

# Configuración general
sonar.projectKey=fermin
sonar.projectName=Fermin
sonar.projectVersion=1.0


##        <sonar.coverage.jacoco.xmlReportPaths>${project.build.directory}/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>

# Configuración de fuentes y tests
sonar.sources=animalitos/servicio/impl/src/main/java
sonar.tests=animalitos/servicio/api/src/test/java
